"""add user_movie_services table

Revision ID: 6897bca69fcb
Revises: bf2ad531dde5
Create Date: 2026-05-09 16:35:31.865036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6897bca69fcb'
down_revision: Union[str, Sequence[str], None] = 'bf2ad531dde5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_movie_services',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('movie_service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'movie_service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_movie_services')
    # ### end Alembic commands ###
