"""add rating and comment to user_moives

Revision ID: bf2ad531dde5
Revises: fdaf570b78fe
Create Date: 2026-04-27 17:50:34.349614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2ad531dde5'
down_revision: Union[str, Sequence[str], None] = 'fdaf570b78fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_movies', sa.Column('rating', sa.SmallInteger(), nullable=True))
    op.add_column('user_movies', sa.Column('comment', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_user_movies_rating_range",
        "user_movies",
        "rating >= 0 AND rating <= 5"
    )
    op.create_check_constraint(
        "ck_movies_vote_average_range",
        "movies",
        "vote_average >= 0.0 AND vote_average <= 10.0"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_movies', 'comment')
    op.drop_column('user_movies', 'rating')
    op.drop_constraint("ck_user_movies_rating_range", "user_movies", type_="check")
    op.drop_constraint("ck_movies_vote_average_range", "movies", type_="check")
    # ### end Alembic commands ###
