"""add movies and user movies

Revision ID: fa14ba0560e9
Revises: 7e1693081889
Create Date: 2026-04-20 17:19:16.536441

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fa14ba0560e9'
down_revision: Union[str, Sequence[str], None] = '7e1693081889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('vote_average', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('user_movies',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('movie_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('LIKED', 'DISLIKED', 'VIEWED', name='usermoviestatus'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'movie_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_movies')
    op.drop_table('movies')
    op.execute("DROP TYPE IF EXISTS usermoviestatus CASCADE;")
    # ### end Alembic commands ###
