"""add_created_at to user_movies

Revision ID: fdaf570b78fe
Revises: 3936c41620a1
Create Date: 2026-04-27 14:52:55.169841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdaf570b78fe'
down_revision: Union[str, Sequence[str], None] = '3936c41620a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_movies', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_movies', 'created_at')
    # ### end Alembic commands ###
